name: Package vue-pc-chat

on:
  push:
    branches: [ package ]
  pull_request:
    branches: [ package ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.18.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.18.x
      - run: npm install -g node-gyp@8.3.0
      - run: npm ci
      - run: npm run cross-package-all
